---
abstract: 'Create a formatted table using characters.'
author:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-UnicodeTable-Simple
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Unicode::EastAsianWidth: 1.30
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/syohex/p5-Text-UnicodeTable-Simple.git
version: 0.02
